version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build-code:
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: npm test
          name: Run tests
      - run:
          command: npm build
          name: Build app
