version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      - run:
          name: Coverage
          command: react-scripts test --coverage --watchAll=false
      - store_test_results:
          path: ./reports/
    resource_class: large

workflows:
  test_my_app:
    jobs:
      - build_and_test
